services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./dev/nginx:/etc/nginx/templates
    networks:
      juicyloopsnet:
        aliases:
          - juicyloops.test

  install-dependencies: 
    image: node:24
    working_dir: /app
    volumes:
      - ./juicyloops:/app
    networks:
      - juicyloopsnet
    command: sh -c "corepack enable && yarn"

  frontend:
    image: node:24
    hostname: frontend
    working_dir: /app
    restart: unless-stopped
    env_file:
      - ./juicyloops/frontend/.env
    volumes:
      - ./juicyloops:/app
      - ./uploads:/uploads
    networks:
      - juicyloopsnet
    depends_on:
      install-dependencies:
        condition: service_completed_successfully
    command: sh -c "corepack enable && exec yarn dev:frontend --host=0.0.0.0 --port=3000"

networks:
  juicyloopsnet:
    driver: bridge